export const GET_PANIER = "GET_PANIER";
export const ADD_PANIER = "ADD_PANIER";
export const UPDATE_PANIER = "UPDATE_PANIER";
export const DELETE_PANIER = "DELETE_PANIER";
export const ADD_TOTAL_PANIER = "ADD_TOTAL_PANIER";
export const GET_TOTAL_PANIER = "GET_TOTAL_PANIER";
